spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/shop
    platform: mysql
    initialization-mode: never
    continue-on-error: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: info
    org.springframework.web: info
  pattern:
    console: "%d %-5level %logger : %msg%n"